[package]
name = "risingwave_frontend"
version = "0.1.5"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1"
assert-impl = "0.1"
async-trait = "0.1"
byteorder = "1.4"
bytes = "1"
clap = { version = "3", features = ["derive"] }
downcast-rs = "1.2"
dyn-clone = "1.0.4"
enum-as-inner = "0.4"
fixedbitset = "0.4.1"
futures = "0.3"
futures-async-stream = "0.2"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
maplit = "1"
num-traits = "0.2"
parking_lot = "0.12"
paste = "1"
pgwire = { path = "../utils/pgwire" }
rand = "0.8"
risingwave_common = { path = "../common" }
risingwave_expr = { path = "../expr" }
risingwave_meta = { path = "../meta" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_source = { path = "../source" }
risingwave_sqlparser = { path = "../sqlparser" }
serde_json = "1"
smallvec = { version = "1.6.1", features = ["serde"] }
thiserror = "1"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tonic = "0.7"
tracing = { version = "0.1" }
uuid = "0.8"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
tempfile = "3"
